name: Update DockerHub Description
on:
  push:
    branches:
      - master
    paths:
      - README.md
      - .github/workflows/sync_dockerhub_description.yml
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: uniwuezpd/ocr4all
        short-description: ${{ github.event.repository.description }}
